version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
      - sqlite_data:/app/db  # Persist SQLite data in a volume
    ports:
      - "8000:8000"
    entrypoint: >
      bash -c "
      python3 manage.py migrate &&
      python3 create_superuser.py &&
      python3 manage.py runserver 0.0.0.0:8000
      "

volumes:
  media_volume:
  sqlite_data:  # Defines the SQLite data volume
