version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: >
      bash -c "
      python3 manage.py migrate &&
      python3 create_superuser.py &&
      python3 manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data:
  media_volume:  # This defines the media volume
